crudapp/urls.py
from django.urls import path

from . import views

app_name = "crudapp"

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('new', views.post_create, name='post_new'),
    path('edit/<int:pk>/', views.post_update, name='post_edit'),
    path('delete/<int:pk>/', views.post_delete, name='post_delete'),
    path('emp', views.emp, name='emp_create'),
    path('show', views.show, name='emp_show'),
    path('edit/<int:id>', views.edit, name='emp_edit'),
    path('update/<int:id>', views.update, name='emp_update'),
    path('delete/<int:id>', views.destroy, name='emp_delete'),
]

ericauto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name = 'home.html'), name = 'home'),
    path('trauto/', include('trauto.urls', namespace = "trauto")),
    path('crud/', include('crudapp.urls', namespace = "crudapp"))

]

trauto/urls.py
from django.urls import path

from . import views

app_name = "trauto"

urlpatterns = [
    path('', views.index, name='index'),
    path('list', views.node_list, name='node_list'),
    path('mail', views.mail)
]

user/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

crudapp/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.urls import reverse


class BlogPost(models.Model):
    title = models.CharField(max_length=400)
    tag = models.CharField(max_length=50)
    author = models.CharField(max_length=120)

    def __unicode__(self):
        return self.title

    def get_post_url(self):
        return reverse('post_edit', kwargs={'pk': self.pk})


class Employee(models.Model):
    eid = models.CharField(max_length=20)
    ename = models.CharField(max_length=100)
    eemail = models.EmailField()
    econtact = models.CharField(max_length=15)

    class Meta:
        db_table = "employee"

trauto/models.py
from django.db import models

# Create your models here.


class NodeInventory(models.Model):
    node_name = models.CharField(max_length = 100)
    node_ip = models.CharField(max_length = 30)
    oss_ip = models.CharField(max_length = 30)
    # domain = models.

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    # add additional fields in here

    def __str__(self):
        return self.email

crudapp/forms.py
from django import forms
from .models import Employee


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'email')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

crudapp/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from crudapp.forms import EmployeeForm
from crudapp.models import BlogPost , Employee


class PostsForm(ModelForm):
    class Meta:
        model = BlogPost
        fields = ['id', 'title', 'tag', 'author']


def post_list(request):
    posts = BlogPost.objects.all()
    data = {'object_list': posts}
    return render(request, 'blog_posts/post_list.html', data)


def post_create(request):
    form = PostsForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('crudapp:post_list')
    return render(request, 'blog_posts/post_form.html', {'form': form})


def post_update(request, pk):
    post = get_object_or_404(BlogPost, pk=pk)
    form = PostsForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('blog_posts:post_list')
    return render(request, 'blog_posts/post_form.html', {'form': form})


def post_delete(request, pk):
    post = get_object_or_404(BlogPost, pk=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('crudapp:post_list')
    return render(request, 'blog_posts/post_delete.html', {'object': post})


def emp(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('crudapp:emp_show')
            except Exception:
                pass
    else:
        form = EmployeeForm()
    return render(request, 'employee/index.html', {'form': form})


def show(request):
    employees = Employee.objects.all()
    return render(request, 'employee/show.html', {'employees': employees})


def edit(request, id):
    employee = Employee.objects.get(id=id)
    return render(request, 'employee/edit.html', {'employee': employee})


def update(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance = employee)
    if form.is_valid():
        form.save()
        return redirect("crudapp:emp_show")
    return render(request, 'employee/edit.html', {'employee': employee})


def destroy(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect("crudapp:emp_show")


trauto/views.py
from django.core.mail import send_mail
from django.core.paginator import Paginator , PageNotAnInteger , EmptyPage
from django.http import HttpResponse
from django.shortcuts import render
import openpyxl
from django.contrib.auth.decorators import login_required

from ericauto import settings
from trauto.models import NodeInventory


@login_required(login_url='/user/login/')
def index(request):
    if "GET" == request.method:
        return render(request, 'file_upload.html', {})
    else:
        excel_file = request.FILES["excel_file"]

        # you may put validations here to check extension or file size

        wb = openpyxl.load_workbook(excel_file)

        # getting all sheets
        # sheets = wb.sheetnames
        # getting active sheet
        # active_sheet = wb.active
        # reading a cell
        # print ( worksheet [ "A1" ].value )

        # getting a particular sheet by name out of many sheets
        worksheet = wb["Sheet1"]
        print(worksheet)

        excel_data = list()
        # iterating over the rows and
        # getting value from each cell in row
        for row in worksheet.iter_rows():
            row_data = list()
            for cell in row:
                row_data.append(str(cell.value))
            excel_data.append(row_data)

        print(excel_data)

        for data in excel_data:
            node = NodeInventory(node_name=data[-1], node_ip=data[1], oss_ip=data[0])
            node.save()
        return render(request, 'file_upload.html', {"excel_data": excel_data})


def mail(request):
    subject = "Greetings"
    msg = "Congratulations for your success"
    to = "shivam.b.gupta@ericsson.com"
    res = send_mail(subject, msg, settings.EMAIL_HOST_USER, [to])
    if res == 1:
        msg = "Mail Sent Successfuly"
    else:
        msg = "Mail could not sent"
    return HttpResponse(msg)


def node_list(request):
    user_list = NodeInventory.objects.all()
    page = request.GET.get('page', 1)

    paginator = Paginator(user_list, 20)

    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    print ( users.paginator.page_range )
    return render(request, 'node_list.html', { 'users': users })

user/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm


class SignUp(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/blog_posts/post_delete.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>Django CRUD application!</title>
  </head>
  <body>
    <div class="container">
      <form method="post">{% csrf_token %}
        Are you sure you want to delete "{{ object }}" ?
        <input class="btn btn-primary" type="submit" value="Submit" />
      </form>
    </div>
  </body>
</html>

templates/blog_posts/post_form.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>Django CRUD application!</title>
  </head>
  <body>
    <div class="container">
      <form  method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Submit" />
      </form>
    </div>
  </body>
</html>

templates/blog_posts/post_list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>Django CRUD application!</title>
  </head>
  <body>
    <div class="container">
        <h1>Blog Post List!</h1>
        <ul>
          {% for post in object_list %}
          <li><p>Post ID: <a href="{% url "crudapp:post_edit" post.id %}">{{ post.id }}</a></p>
          <p>Title: {{ post.title }}</p>
            <a href="{% url "crudapp:post_delete" post.id %}">Delete</a>
          </li>
          {% endfor %}
        </ul>

        <a href="{% url "crudapp:post_new" %}">New Blog post entry</a>
    </div>
  </body>
</html>

templates/employee/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
         <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Index</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/update/{{employee.id}}">
        {% csrf_token %}
    <div class="container-fluid">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Id:</label>
    <div class="col-sm-4">
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Name:</label>
    <div class="col-sm-4">
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Email:</label>
    <div class="col-sm-4">
        <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Contact:</label>
    <div class="col-sm-4">
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>
    </div>
</form>

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

templates/employee/index.html
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Index</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="emp">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Enter Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Id:</label>
    <div class="col-sm-4">
      {{ form.eid }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Name:</label>
    <div class="col-sm-4">
      {{ form.ename }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Email:</label>
    <div class="col-sm-4">
      {{ form.eemail }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Contact:</label>
    <div class="col-sm-4">
      {{ form.econtact }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
    </div>
</form>
 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

templates/employee/show.html
<!DOCTYPE html>
<html lang="en">
<head>
          <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Employee Records</title>
     {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Employee ID</th>
        <th>Employee Name</th>
        <th>Employee Email</th>
        <th>Employee Contact</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
{% for employee in employees %}
    <tr>
        <td>{{ employee.eid }}</td>
        <td>{{ employee.ename }}</td>
        <td>{{ employee.eemail }}</td>
        <td>{{ employee.econtact }}</td>
        <td>
            <a href="edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
            <a href="delete/{{ employee.id }}">Delete</a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="emp" class="btn btn-primary">Add New Record</a></center>
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

templates/file_upload.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body style="margin-top: 30px;margin-left: 30px;">
    <form action="{% url "trauto:index" %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <input type="file"
      title="Upload excel file"
      name="excel_file"
      style="border: 1px solid black; padding: 5px;"
      required="required">
      <p>
        <input type="submit"
        value="Upload"
        style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
      </form>
      <!--<p></p>-->
      <!--<hr>-->
      <!--{% for row in excel_data %}-->
        <!--{% for cell in row %}-->
          <!--{{ cell }}&nbsp;&nbsp;-->
        <!--{% endfor %}-->
        <!--<br>-->
      <!--{% endfor %}-->
      <div class="container">
        <h2>Basic Table</h2>
        <p>Excel Sheet Data</p>
        <table class="table  table-bordered table-striped table-hover ">
          <thead class="thead-dark">
            <tr>
                <th class="text-capitalize" scope="col">S.No</th>
                {% for tr in  excel_data|slice:"1" %}
                    {% for th in tr %}
                        <th class="text-capitalize" scope="col">{{ th}}</th>
                    {% endfor %}
                {% endfor %}
            </tr>
          </thead>
          <tbody>
            {% for row in excel_data|slice:"1:" %}
            <tr>
                <th> {{ forloop.counter }}</th>
                {% for data in row %}

                    <th class="font-weight-normal">{{data}}</th>
                {% endfor %}
                </tr>
          {% endfor %}

          </tbody>
        </table>
      </div>
  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    </body>
  </html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
<p><a href="{% url 'logout' %}">logout</a></p>
<p><a href="{% url 'password_reset' %}">reset password</a></p>
{% else %}
  <p>You are not logged in</p>

  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

templates/node_list.html
<!doctype html>
<html lang="en">
  <head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  </head>
  <body>
    <div class="container mt-3">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>Server IP</th>
            <th>Node IP</th>
            <th>Node Name</th>
          </tr>
        </thead>
        <tbody>
          {% for user in users %}
            <tr>
              <td>{{ user.id }}</td>
              <td>{{ user.oss_ip }}</td>
              <td>{{ user.node_ip }}</td>
              <td>{{ user.node_name }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      {% if users.has_other_pages %}
        <ul class="pagination">
          {% if users.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ users.previous_page_number }}">&laquo;</a></li>
          {% else %}
            <li class="page-item" class="disabled"><span>&laquo;</span></li>
          {% endif %}
          {% for i in users.paginator.page_range %}
            {% if users.number == i %}
              <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
            {% else %}
              <li class="page-item"><a class="page-link"  href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
          {% endfor %}
          {% if users.has_next %}
            <li class="page-item"><a class="page-link"  href="?page={{ users.next_page_number }}">&raquo;</a></li>
          {% else %}
            <li class="page-item" class="disabled"><span>&raquo;</span></li>
          {% endif %}
        </ul>
      {% endif %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  </body>
</html>

templates/pagination.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
{% if users.has_other_pages %}
  <ul class="pagination justify-content-center">
    {% if users.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ users.previous_page_number }}">Previous</a></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="javascript:void(0);">1</a></li>
    <li class="page-item"><a class="page-link" href="javascript:void(0);">2</a></li>
    <li class="page-item"><a class="page-link" href="javascript:void(0);">Next</a></li>
  </ul>
  {% endif %}

</div>

</body>
</html>

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}